// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package ethgasstation

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson958d199eDecodeGitlabLunuIoLunusolutionsEthScannerNodeCrawlerInternalEthgasstation(in *jlexer.Lexer, out *Station) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "fast":
			out.Fast = int64(in.Int64())
		case "fastest":
			out.Fastest = int64(in.Int64())
		case "safeLow":
			out.SafeLow = int64(in.Int64())
		case "average":
			out.Average = int64(in.Int64())
		case "block_time":
			out.BlockTime = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson958d199eEncodeGitlabLunuIoLunusolutionsEthScannerNodeCrawlerInternalEthgasstation(out *jwriter.Writer, in Station) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"fast\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Fast))
	}
	{
		const prefix string = ",\"fastest\":"
		out.RawString(prefix)
		out.Int64(int64(in.Fastest))
	}
	{
		const prefix string = ",\"safeLow\":"
		out.RawString(prefix)
		out.Int64(int64(in.SafeLow))
	}
	{
		const prefix string = ",\"average\":"
		out.RawString(prefix)
		out.Int64(int64(in.Average))
	}
	{
		const prefix string = ",\"block_time\":"
		out.RawString(prefix)
		out.Float64(float64(in.BlockTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Station) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson958d199eEncodeGitlabLunuIoLunusolutionsEthScannerNodeCrawlerInternalEthgasstation(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Station) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson958d199eEncodeGitlabLunuIoLunusolutionsEthScannerNodeCrawlerInternalEthgasstation(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Station) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson958d199eDecodeGitlabLunuIoLunusolutionsEthScannerNodeCrawlerInternalEthgasstation(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Station) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson958d199eDecodeGitlabLunuIoLunusolutionsEthScannerNodeCrawlerInternalEthgasstation(l, v)
}
